### ISSUE TITLE
Cannot find module '@poppinss/file-generator'

### ISSUE THREAD

**Issue by VladyslavP98** [poppinss/file-generator#3]
## Description

I received error on latest package version. I develop some package for adonis and this package are used as fold dependency.
```Cannot find module '@poppinss/file-generator' from 'node_modules/@adonisjs/http server/node_modules/@poppinss/utils/build/src/Helpers/index.js'```

I think this issue related to this [https://github.com/poppinss/file-generator/commit/58ef657490d97393da1fdfa7b2b9901c860fea7f](commit)
All works perfectly with version `1.0.1`
## Package version
1.0.2

## Node.js and npm version
Reproduced on:
- Node 14.18.1 & NPM 6.14.15
- Node 16.14.2 & NPM 8.5.0

**Comment by thetutlage** [comment]
That shouldn't be creating an issue. What version of `@adonisjs/core` are you using?

**Comment by VladyslavP98** [comment]
I have an issues with `@adonis/fold` with version `8.2.0`

**Comment by VladyslavP98** [comment]
I resolved my issue. Now all works fine. If you have a time you can try to clone [this brach](https://github.com/VladyslavParashchenko/adonis-provider-tester/tree/test-version) and run tests.  Maybe you will find the reason.

PS: I use this package for testing adonis providers. It would be nice if we can run adonis in memory without this hacks.
